version: '3'
services:

  mariadb:
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  redis:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"

